# type: ignore
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = "3.10"

_lr_method = "LALR"

_lr_signature = "DELIMITER EQUAL FLOAT INT LPAREN LSQUARE RPAREN RSQUARE STRING UNQUOTED_STRING\n        px : px key_value\n           | key_value\n        \n        key_value : key EQUAL values\n        \n        key : key_with_translation\n            | key_with_and_stub\n            | simple_key\n        \n        simple_key : UNQUOTED_STRING\n        \n        key_with_translation : UNQUOTED_STRING LSQUARE UNQUOTED_STRING RSQUARE\n        \n        key_with_and_stub : UNQUOTED_STRING LPAREN STRING RPAREN\n        \n        values : values DELIMITER value\n               | value\n        \n        value : UNQUOTED_STRING\n              | FLOAT\n              | INT\n              | STRING\n        "

_lr_action_items = {
    "UNQUOTED_STRING": (
        [
            0,
            1,
            2,
            8,
            9,
            10,
            12,
            13,
            14,
            15,
            16,
            17,
            20,
            23,
        ],
        [
            7,
            7,
            -2,
            -1,
            14,
            18,
            -3,
            -11,
            -12,
            -13,
            -14,
            -15,
            14,
            -10,
        ],
    ),
    "$end": (
        [
            1,
            2,
            8,
            12,
            13,
            14,
            15,
            16,
            17,
            23,
        ],
        [
            0,
            -2,
            -1,
            -3,
            -11,
            -12,
            -13,
            -14,
            -15,
            -10,
        ],
    ),
    "EQUAL": (
        [
            3,
            4,
            5,
            6,
            7,
            21,
            22,
        ],
        [
            9,
            -4,
            -5,
            -6,
            -7,
            -8,
            -9,
        ],
    ),
    "LSQUARE": (
        [
            7,
        ],
        [
            10,
        ],
    ),
    "LPAREN": (
        [
            7,
        ],
        [
            11,
        ],
    ),
    "FLOAT": (
        [
            9,
            20,
        ],
        [
            15,
            15,
        ],
    ),
    "INT": (
        [
            9,
            20,
        ],
        [
            16,
            16,
        ],
    ),
    "STRING": (
        [
            9,
            11,
            20,
        ],
        [
            17,
            19,
            17,
        ],
    ),
    "DELIMITER": (
        [
            12,
            13,
            14,
            15,
            16,
            17,
            23,
        ],
        [
            20,
            -11,
            -12,
            -13,
            -14,
            -15,
            -10,
        ],
    ),
    "RSQUARE": (
        [
            18,
        ],
        [
            21,
        ],
    ),
    "RPAREN": (
        [
            19,
        ],
        [
            22,
        ],
    ),
}

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_action:
            _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {
    "px": (
        [
            0,
        ],
        [
            1,
        ],
    ),
    "key_value": (
        [
            0,
            1,
        ],
        [
            2,
            8,
        ],
    ),
    "key": (
        [
            0,
            1,
        ],
        [
            3,
            3,
        ],
    ),
    "key_with_translation": (
        [
            0,
            1,
        ],
        [
            4,
            4,
        ],
    ),
    "key_with_and_stub": (
        [
            0,
            1,
        ],
        [
            5,
            5,
        ],
    ),
    "simple_key": (
        [
            0,
            1,
        ],
        [
            6,
            6,
        ],
    ),
    "values": (
        [
            9,
        ],
        [
            12,
        ],
    ),
    "value": (
        [
            9,
            20,
        ],
        [
            13,
            23,
        ],
    ),
}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if not _x in _lr_goto:
            _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> px", "S'", 1, None, None, None),
    ("px -> px key_value", "px", 2, "p_px", "parser.py", 34),
    ("px -> key_value", "px", 1, "p_px", "parser.py", 35),
    ("key_value -> key EQUAL values", "key_value", 3, "p_key_value", "parser.py", 44),
    ("key -> key_with_translation", "key", 1, "p_key", "parser.py", 52),
    ("key -> key_with_and_stub", "key", 1, "p_key", "parser.py", 53),
    ("key -> simple_key", "key", 1, "p_key", "parser.py", 54),
    ("simple_key -> UNQUOTED_STRING", "simple_key", 1, "p_simple_key", "parser.py", 61),
    (
        "key_with_translation -> UNQUOTED_STRING LSQUARE UNQUOTED_STRING RSQUARE",
        "key_with_translation",
        4,
        "p_key_with_translation",
        "parser.py",
        75,
    ),
    (
        "key_with_and_stub -> UNQUOTED_STRING LPAREN STRING RPAREN",
        "key_with_and_stub",
        4,
        "p_key_with_and_stub",
        "parser.py",
        89,
    ),
    ("values -> values DELIMITER value", "values", 3, "p_values", "parser.py", 104),
    ("values -> value", "values", 1, "p_values", "parser.py", 105),
    ("value -> UNQUOTED_STRING", "value", 1, "p_value", "parser.py", 115),
    ("value -> FLOAT", "value", 1, "p_value", "parser.py", 116),
    ("value -> INT", "value", 1, "p_value", "parser.py", 117),
    ("value -> STRING", "value", 1, "p_value", "parser.py", 118),
]
