name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-and-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and setup poetry
        run: |
          pip install poetry==1.1.4
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
      - name: Mypy
        run: poetry run mypy px
      - name: test
        run: poetry run pytest
